# Generated by Django 4.2.14 on 2024-07-21 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Assignments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField()),
                ('status', models.BooleanField(default=False)),
                ('estimation', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='Assignments.assignmentsmodel')),
            ],
        ),
    ]
