# Generated by Django 4.2.14 on 2024-07-21 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Рейтинг курса от 1 до 5')),
                ('review_text', models.TextField(help_text='Текст отзыва о курсе')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания отзыва')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Courses.coursesmodel')),
            ],
        ),
    ]
