# Generated by Django 4.2.14 on 2024-07-24 22:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Courses', '0004_alter_coursesmodel_managers'),
        ('Reviews', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewsModel',
        ),
    ]
