# Generated by Django 4.2.14 on 2024-07-21 23:23

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='coursesmodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='coursesmodel',
            name='name',
            field=models.CharField(),
        ),
    ]
