# Generated by Django 4.2.14 on 2024-07-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_alter_coursesmodel_managers_alter_coursesmodel_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='coursesmodel',
            managers=[
            ],
        ),
    ]
