# Generated by Django 4.2.14 on 2024-07-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField(help_text='Дата и время, к которым должно быть сдано задание')),
            ],
        ),
    ]
