# Generated by Django 4.2.14 on 2024-07-21 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lessons', '0001_initial'),
        ('Assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsmodel',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='Lessons.lessonsmodel'),
        ),
    ]
