# Generated by Django 4.2.14 on 2024-07-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False, help_text='Отметьте, если уведомление было прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания уведомления')),
            ],
        ),
    ]
