# Generated by Django 4.2.14 on 2024-07-24 21:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notifications', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='NotificationsModel',
        ),
    ]
